[package]
name= "image steganography"
version = "0.0.1"
edition ="2021"

[dependencies]
pixelate = { git = "https://github.com/Anoncomrade993/pixelate.git",tag="0.1.0"}
image = "0.24.9"
serde_json = "1.0.114"
base64 = "0.21.7"